name: Application CI
on:
  push:
    branches: [ "main", "ci-config" ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install vue cli for build
        run: npm install @vue/cli-service
      - name: Build project
        run: npm run build
      - name: Echo domain cname
        run: cd docs && echo 'tonglec.org' > CNAME