name: Application CI
on:
  push:
    branches:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: npm run build
      - name: Echo domain cname
        run: cd docs && echo 'tonglec.org' > CNAME