name: Application CI
on:
  push:
    branches: [ "dev" ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM Modules
        run: npm install
      - name: Generate project
        run: |
          npm run generate
      - name: Remove docs
        run: |
          rm -rf docs/
      - name: Move public to docs
        run: |
          mkdir docs
          cp -R .output/public/* docs/
          echo -e 'www.tonglec.org\ntonglec.org' > CNAME
      - name: Push results to origin
        run: |
          git config --global user.name 'TongLeC'
          git config --global user.email 'TongLeChinese@tonglec.org'
          git add docs
          git commit -m "Build /docs for static serve"
          git push