name: Application CI
on:
  push:
    branches: [ "dev" ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install vue cli for build
        run: npm install @vue/cli-service
      - name: Build project
        run: |
          npm run build
          echo 'tonglec.org' > docs/CNAME
      - name: Push results to origin
        run: |
          git config --global user.name 'TongLeC'
          git config --global user.email 'TongLeChinese@tonglec.org'
          git add docs
          git commit -m "Build /docs for static serve"
          git push